theme: jekyll-theme-minimal
title: YOLOv5 and YOLOv8 in Indoor and Outdoor Usage
description: This is the project webpage for CS766 Computer Vision


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
