theme: jekyll-theme-minimal
title: Yolo5/8 in Indoor and outdoor usage
description: This is the project webpage for CS766 Computer Vision
[View Presentation Slides](https://github.com/jakie528/YOLOv5-and-YOLOv8-in-Indoor-and-Outdoor-Usage/blob/ce9bd915c2340af56acb036ee8ca2d331a7b2264/Visual_Detection_CS766.pdf)

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
